# costmap_common_params.yaml

# Created by: Robson Rogério Dutra Pereira on 01.Out.2022
# Last Modified: rrdpereira

# Description: This is the costmap common definitions for a differential robot.
# Diameter footprint 55.85 cm
robot_radius: 0.27925

transform_tolerance: 0.2
map_type: "costmap"
subscribe_to_updates: true

always_send_full_costmap: true

obstacle_2d_layer:
  enabled: true
  obstacle_range: 8.0
  raytrace_range: 10.0
  inflation_radius: 1.0
  track_unknown_space: true
  combination_method: 1
  observation_sources: "laser_scan_sensor"
  laser_scan_sensor:
    data_type: "LaserScan"
    topic: "scan"
    marking: true
    clearing: true
    inf_is_valid: true    

inflation_layer:
  enabled:              true
  cost_scaling_factor:  10.0
  inflation_radius:     1.0

static_layer:
  enabled:              true
  map_topic:            "map"